variable "name_prefix" {}
variable "default_tags" {}
variable "function_name" {}
variable "description" {}
variable "handler" {}
variable "runtime" {}
variable "source_path" {}
variable "environment_variables" {}
variable "cloudwatch_schedule_expression" {}
variable "access_private_network" {}
variable "vpc_subnet_ids" {}
variable "vpc_security_group_ids" {}