variable "region" {}
variable "environment" {}
variable "project_name" {}
variable "name_prefix" {}
variable "default_tags" {}
variable "alias_name" {}
variable "vpc_id" {}
variable "cluster" {}
variable "task_role" {}
variable "lb_listeners" {}
variable "memory_reservation" {}
variable "service_config" {}
variable "task_execution_role" {}
variable "subnet_ids" {}
variable "security_group_id" {}
variable "kms_alias_arn" {}