variable "environment" {}
variable "project_name" {}
variable "name_prefix" {}
variable "default_tags" {}
variable "region" {}
variable "ecr_arns" {}
variable "app_bucket" {}
variable "cluster_arn" {}
variable "task_definitions_arns" {}
variable "services_config" {}
variable "kms_alias" {}
variable "bastion_arn" {}
variable "cloudwatch_arns" {}