name: "Python Django - Code Quality Check"

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    env:
      ENV: test
      CORS_ALLOW_ALL_ORIGINS: True
      DJANGO_ALLOWED_HOSTS: "*,"
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            ./src/config/requirements.txt
            ./src/config/requirements/test.txt
      - run: make install-test-req
      - run: make test

  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-black@v2
        with:
          level: "error"
          reporter: "github-check"
          filter_mode: "nofilter"
