variable "environment" {}
variable "region" {}
variable "project_name" {}
variable "name_prefix" {}
variable "default_tags" {}
variable "vpc_id" {}
variable "subnet_ids" {}
variable "security_group_id" {}
variable "certificate_arn" {}