CREATE DATABASE IF NOT EXISTS ${database_name};

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES, CREATE VIEW, EVENT, TRIGGER, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE 
ON ${database_name}.* TO '${database_name}'@'%' IDENTIFIED BY '${database_password}';

FLUSH PRIVILEGES;